site_name: My Project

site_url: http://api.mbodi.ai/mbdata-docs/
use_directory_urls: false

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: crystal
      watch: [.]

markdown_extensions:
  - pymdownx.highlight
  - deduplicate-toc
